#ifndef _PROGRAM4_H_
#define _PROGRAM4_H_

/*
 * Filename: program.h
 * Date:     04/03/2020
 * Author:   Michael Boyd
 * Email:    mnb170030@utdallas.edu
 * Version:  1.0
 * Copyright 2020, All Rights Reserved
 *
 * Description:
 *
 *      Call the yylex() function generated by flex.
 *
 */

enum {NameToken=1, IdentifierToken, Name_Initial_Token, RomanToken, SrToken, JrToken, EOLToken, IntToken, CommaToken, DashToken, HashToken};

#endif /* _PROGRAM4_H_ */
